import { ChildProcess, spawn } from 'child_process'
import fs from 'fs'
import net from 'net'
import path from 'path'
import { getAppDataDir } from './app-paths'
import { getProjectAssetsPath } from './app-state'
import { getCurrentDir, isDev } from './config'
import { logger, writeLog } from './logger'
import { getAuthToken, getBackendUrl, getPythonPath } from './python-backend'

type ComfyUIState = 'stopped' | 'starting' | 'running' | 'error'

export interface ComfyUIStatus {
  state: ComfyUIState
  url?: string
  port?: number
  error?: string
  ltxDataPath: string
  ltxModelsPath: string
  inputPath: string
  outputPath: string
  userPath: string
}

interface ComfyUIPaths {
  rootPath: string
  ltxVideoCustomNodePath: string
  ltxDataPath: string
  ltxModelsPath: string
  inputPath: string
  outputPath: string
  tempPath: string
  userPath: string
  extraModelPathsConfig: string
}

let comfyProcess: ChildProcess | null = null
let comfyState: ComfyUIState = 'stopped'
let comfyUrl: string | undefined
let comfyPort: number | undefined
let comfyError: string | undefined
let startPromise: Promise<ComfyUIStatus> | null = null
let lastPaths: ComfyUIPaths | null = null

const START_PORT = 8188
const START_TIMEOUT_MS = 300_000

function ensureDir(dir: string): void {
  fs.mkdirSync(dir, { recursive: true })
}

function getComfyUIRoot(): string {
  if (isDev) {
    return path.join(getCurrentDir(), 'ComfyUI')
  }
  return path.join(process.resourcesPath, 'ComfyUI')
}

function getDefaultModelsPath(): string {
  const modelsPath = path.join(getAppDataDir(), 'models')
  ensureDir(modelsPath)
  return modelsPath
}

function getLtxVideoSourcePath(): string {
  return path.join(getCurrentDir(), 'ComfyUI-LTXVideo')
}

function copyLtxVideoCustomNode(sourcePath: string, targetPath: string): void {
  fs.cpSync(sourcePath, targetPath, {
    recursive: true,
    force: true,
    filter: (src) => {
      const relativePath = path.relative(sourcePath, src)
      if (!relativePath) return true
      return !relativePath.split(path.sep).includes('.git')
    },
  })
}

function ensureLtxVideoCustomNode(rootPath: string): string {
  const targetPath = path.join(rootPath, 'custom_nodes', 'ComfyUI-LTXVideo')
  const sourcePath = getLtxVideoSourcePath()

  ensureDir(path.dirname(targetPath))
  if (fs.existsSync(sourcePath) && path.resolve(sourcePath) !== path.resolve(targetPath)) {
    copyLtxVideoCustomNode(sourcePath, targetPath)
  }

  if (!fs.existsSync(path.join(targetPath, '__init__.py'))) {
    throw new Error(
      `ComfyUI-LTXVideo was not found. Expected it at ${targetPath}` +
        (fs.existsSync(sourcePath) ? '' : ` or ${sourcePath}`),
    )
  }

  return targetPath
}

async function getEffectiveModelsPath(): Promise<string> {
  const fallback = getDefaultModelsPath()
  const backendUrl = getBackendUrl()
  if (!backendUrl) {
    return fallback
  }

  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), 1500)
  try {
    const headers: Record<string, string> = {}
    const token = getAuthToken()
    if (token) headers.Authorization = `Bearer ${token}`
    const response = await fetch(`${backendUrl}/api/settings`, {
      headers,
      signal: controller.signal,
    })
    if (!response.ok) {
      return fallback
    }
    const settings = await response.json() as { modelsDir?: unknown }
    const configured = typeof settings.modelsDir === 'string' ? settings.modelsDir.trim() : ''
    if (configured) {
      ensureDir(configured)
      return path.resolve(configured)
    }
  } catch {
    return fallback
  } finally {
    clearTimeout(timeout)
  }

  return fallback
}

function yamlString(value: string): string {
  return JSON.stringify(value.replace(/\\/g, '/'))
}

function writeExtraModelPathsConfig(modelsPath: string, configPath: string): void {
  ensureDir(path.dirname(configPath))
  const body = [
    '# Generated by LTX Desktop. Do not edit while the app is running.',
    'ltx_models:',
    `  base_path: ${yamlString(modelsPath)}`,
    '  is_default: true',
    '  checkpoints: |',
    '    .',
    '    checkpoints',
    '  diffusion_models: |',
    '    .',
    '    diffusion_models',
    '    unet',
    '  loras: |',
    '    .',
    '    loras',
    '  text_encoders: |',
    '    gemma-3-12b-it-qat-q4_0-unquantized',
    '    text_encoders',
    '    clip',
    '  vae: |',
    '    vae',
    '  clip_vision: |',
    '    clip_vision',
    '  style_models: |',
    '    style_models',
    '  embeddings: |',
    '    embeddings',
    '  diffusers: |',
    '    diffusers',
    '    Z-Image-Turbo',
    '  vae_approx: |',
    '    vae_approx',
    '  controlnet: |',
    '    controlnet',
    '    t2i_adapter',
    '  gligen: |',
    '    gligen',
    '  upscale_models: |',
    '    .',
    '    upscale_models',
    '  latent_upscale_models: |',
    '    latent_upscale_models',
    '  hypernetworks: |',
    '    hypernetworks',
    '  photomaker: |',
    '    photomaker',
    '  classifiers: |',
    '    classifiers',
    '  model_patches: |',
    '    model_patches',
    '  audio_encoders: |',
    '    audio_encoders',
    '  background_removal: |',
    '    background_removal',
    '  frame_interpolation: |',
    '    frame_interpolation',
    '  geometry_estimation: |',
    '    geometry_estimation',
    '  optical_flow: |',
    '    optical_flow',
    '  detection: |',
    '    detection',
    '',
  ].join('\n')
  fs.writeFileSync(configPath, body, 'utf-8')
}

async function buildComfyUIPaths(): Promise<ComfyUIPaths> {
  const rootPath = getComfyUIRoot()
  const ltxVideoCustomNodePath = ensureLtxVideoCustomNode(rootPath)
  const ltxDataPath = getProjectAssetsPath()
  const ltxModelsPath = await getEffectiveModelsPath()
  const inputPath = ltxDataPath
  const outputPath = path.join(ltxDataPath, 'comfyui-output')
  const tempPath = path.join(ltxDataPath, '.comfyui-temp')
  const userPath = path.join(ltxDataPath, '.comfyui-user')
  const extraModelPathsConfig = path.join(getAppDataDir(), 'comfyui', 'extra_model_paths.yaml')

  for (const dir of [ltxDataPath, ltxModelsPath, inputPath, outputPath, tempPath, userPath]) {
    ensureDir(dir)
  }
  writeExtraModelPathsConfig(ltxModelsPath, extraModelPathsConfig)

  return {
    rootPath,
    ltxVideoCustomNodePath,
    ltxDataPath,
    ltxModelsPath,
    inputPath,
    outputPath,
    tempPath,
    userPath,
    extraModelPathsConfig,
  }
}

function getPathsForStatus(): ComfyUIPaths {
  if (lastPaths) return lastPaths
  const rootPath = getComfyUIRoot()
  const ltxDataPath = getProjectAssetsPath()
  const ltxModelsPath = getDefaultModelsPath()
  return {
    rootPath,
    ltxVideoCustomNodePath: path.join(rootPath, 'custom_nodes', 'ComfyUI-LTXVideo'),
    ltxDataPath,
    ltxModelsPath,
    inputPath: ltxDataPath,
    outputPath: path.join(ltxDataPath, 'comfyui-output'),
    tempPath: path.join(ltxDataPath, '.comfyui-temp'),
    userPath: path.join(ltxDataPath, '.comfyui-user'),
    extraModelPathsConfig: path.join(getAppDataDir(), 'comfyui', 'extra_model_paths.yaml'),
  }
}

function statusFromState(): ComfyUIStatus {
  const paths = getPathsForStatus()
  return {
    state: comfyState,
    url: comfyUrl,
    port: comfyPort,
    error: comfyError,
    ltxDataPath: paths.ltxDataPath,
    ltxModelsPath: paths.ltxModelsPath,
    inputPath: paths.inputPath,
    outputPath: paths.outputPath,
    userPath: paths.userPath,
  }
}

function getFreePort(startPort: number): Promise<number> {
  return new Promise((resolve, reject) => {
    const server = net.createServer()
    server.unref()
    server.on('error', (error: NodeJS.ErrnoException) => {
      if (error.code === 'EADDRINUSE') {
        void getFreePort(startPort + 1).then(resolve, reject)
        return
      }
      reject(error)
    })
    server.listen(startPort, '127.0.0.1', () => {
      const address = server.address()
      const port = typeof address === 'object' && address ? address.port : startPort
      server.close(() => resolve(port))
    })
  })
}

async function probeComfyUI(url: string, timeoutMs = 1200): Promise<boolean> {
  const controller = new AbortController()
  const timeout = setTimeout(() => controller.abort(), timeoutMs)
  try {
    const response = await fetch(url, { signal: controller.signal })
    return response.ok
  } catch {
    return false
  } finally {
    clearTimeout(timeout)
  }
}

function waitForComfyUIReady(url: string, timeoutMs: number): Promise<void> {
  const startedAt = Date.now()
  return new Promise((resolve, reject) => {
    const tick = async () => {
      if (await probeComfyUI(url)) {
        resolve()
        return
      }
      if (Date.now() - startedAt > timeoutMs) {
        reject(new Error('ComfyUI did not become ready before the startup timeout.'))
        return
      }
      setTimeout(tick, 1000)
    }
    void tick()
  })
}

function buildLaunchCommand(paths: ComfyUIPaths, comfyArgs: string[]): { command: string; args: string[]; cwd: string } {
  const isWindows = process.platform === 'win32'
  const venvPython = isWindows
    ? path.join(paths.rootPath, '.venv', 'Scripts', 'python.exe')
    : path.join(paths.rootPath, '.venv', 'bin', 'python')

  if (fs.existsSync(venvPython)) {
    return {
      command: venvPython,
      args: ['-u', 'main.py', ...comfyArgs],
      cwd: paths.rootPath,
    }
  }

  if (isDev) {
    const ltxVideoRequirements = path.join(paths.ltxVideoCustomNodePath, 'requirements.txt')
    const requirementArgs = [
      '--with-requirements',
      path.join(paths.rootPath, 'requirements.txt'),
    ]
    if (fs.existsSync(ltxVideoRequirements)) {
      requirementArgs.push('--with-requirements', ltxVideoRequirements)
    }

    return {
      command: 'uv',
      args: [
        'run',
        '--project',
        path.join(getCurrentDir(), 'backend'),
        ...requirementArgs,
        'python',
        '-u',
        path.join(paths.rootPath, 'main.py'),
        ...comfyArgs,
      ],
      cwd: paths.rootPath,
    }
  }

  return {
    command: getPythonPath(),
    args: ['-u', path.join(paths.rootPath, 'main.py'), ...comfyArgs],
    cwd: paths.rootPath,
  }
}

function logComfyOutput(level: 'INFO' | 'ERROR', output: string): void {
  const tag = level === 'INFO' ? '[ComfyUI]' : '[ComfyUI Error]'
  if (level === 'INFO') {
    console.log(`${tag} ${output}`)
  } else {
    console.error(`${tag} ${output}`)
  }
  for (const line of output.split('\n')) {
    const trimmed = line.trimEnd()
    if (trimmed) writeLog(level, 'ComfyUI', trimmed)
  }
}

export function getComfyUIStatus(): ComfyUIStatus {
  return statusFromState()
}

export async function startComfyUI(): Promise<ComfyUIStatus> {
  if (startPromise) {
    return startPromise
  }

  if (comfyState === 'running' && comfyUrl && await probeComfyUI(comfyUrl)) {
    return statusFromState()
  }

  if (comfyProcess) {
    stopComfyUI()
  }

  startPromise = (async () => {
    const paths = await buildComfyUIPaths()
    lastPaths = paths

    if (!fs.existsSync(path.join(paths.rootPath, 'main.py'))) {
      throw new Error(`ComfyUI was not found at ${paths.rootPath}`)
    }

    const port = await getFreePort(START_PORT)
    const url = `http://127.0.0.1:${port}`
    const comfyArgs = [
      '--listen', '127.0.0.1',
      '--port', String(port),
      '--input-directory', paths.inputPath,
      '--output-directory', paths.outputPath,
      '--temp-directory', paths.tempPath,
      '--user-directory', paths.userPath,
      '--extra-model-paths-config', paths.extraModelPathsConfig,
      '--disable-auto-launch',
      '--enable-cors-header', '*',
      '--log-stdout',
    ]
    const launch = buildLaunchCommand(paths, comfyArgs)

    comfyState = 'starting'
    comfyUrl = url
    comfyPort = port
    comfyError = undefined

    logger.info(`Starting ComfyUI: ${launch.command} ${launch.args.join(' ')}`)
    comfyProcess = spawn(launch.command, launch.args, {
      cwd: launch.cwd,
      env: {
        ...process.env,
        PYTHONUNBUFFERED: '1',
        HF_HUB_DISABLE_TELEMETRY: '1',
        DO_NOT_TRACK: '1',
        LTX_MEDIA_ROOT: paths.ltxDataPath,
        LTX_MODELS_DIR: paths.ltxModelsPath,
        PYTORCH_ENABLE_MPS_FALLBACK: '1',
      },
      stdio: ['ignore', 'pipe', 'pipe'],
    })

    let exitedBeforeReady = false
    let exitCode: number | null = null
    let startupPending = true

    const exitPromise = new Promise<never>((_resolve, reject) => {
      comfyProcess?.on('error', (error) => {
        if (startupPending) {
          comfyState = 'error'
          comfyError = error.message
          reject(error)
          return
        }
        comfyState = 'error'
        comfyError = error.message
      })

      comfyProcess?.on('exit', (code) => {
        exitCode = code
        comfyProcess = null
        if (startupPending) {
          exitedBeforeReady = true
          comfyState = 'error'
          comfyError = `ComfyUI exited during startup with code ${code ?? 'unknown'}`
          reject(new Error(comfyError))
          return
        }

        if (comfyState === 'running') {
          comfyState = 'stopped'
          comfyUrl = undefined
          comfyPort = undefined
        }
      })
    })

    comfyProcess.stdout?.on('data', (data: Buffer) => {
      logComfyOutput('INFO', data.toString())
    })
    comfyProcess.stderr?.on('data', (data: Buffer) => {
      logComfyOutput('ERROR', data.toString())
    })

    try {
      await Promise.race([waitForComfyUIReady(url, START_TIMEOUT_MS), exitPromise])
    } catch (error) {
      if (!exitedBeforeReady && comfyProcess) {
        comfyProcess.kill('SIGTERM')
      }
      comfyState = 'error'
      comfyError = error instanceof Error ? error.message : String(error)
      throw error
    }

    startupPending = false
    if (exitCode !== null) {
      throw new Error(`ComfyUI exited during startup with code ${exitCode}`)
    }

    comfyState = 'running'
    comfyUrl = url
    comfyPort = port
    return statusFromState()
  })()

  try {
    return await startPromise
  } finally {
    startPromise = null
  }
}

export function stopComfyUI(): void {
  if (!comfyProcess) {
    if (comfyState !== 'running') {
      comfyState = 'stopped'
      comfyError = undefined
    }
    return
  }

  logger.info('Stopping ComfyUI...')
  const pid = comfyProcess.pid
  comfyProcess.kill('SIGTERM')
  comfyProcess = null
  comfyState = 'stopped'
  comfyUrl = undefined
  comfyPort = undefined
  comfyError = undefined

  if (pid) {
    setTimeout(() => {
      try {
        process.kill(pid, 0)
        process.kill(pid, 'SIGKILL')
      } catch {
        // Process already exited.
      }
    }, 5000)
  }
}
